trigger:
- main

pool:
  name: MYLOCALPOOLs

steps:

- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- script: |
    echo Creating deployment folder
    if not exist deployed mkdir deployed

    echo Copying jar file
    copy target\*.jar deployed\

    dir deployed
  displayName: 'Deploy JAR'

- script: |
    echo Running the JAR file...
    java -jar deployed\finaldevops-1.0.jar
  displayName: 'Run Application'